# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comments-srv

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("comments-srv", :syntax => :proto2) do
  end
end

