# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comments-srv/comments.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("comments-srv/comments.proto", :syntax => :proto3) do
    add_message "CreateRequest" do
      optional :comment, :message, 1, "Comment"
    end
    add_message "CreateResponse" do
      optional :comment, :message, 1, "Comment"
    end
    add_message "Comment" do
      optional :uuid, :string, 1
      optional :user_uuid, :string, 2
      optional :post_uuid, :string, 3
      optional :text, :string, 4
      optional :created_at, :int64, 5
    end
  end
end

CreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CreateRequest").msgclass
CreateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CreateResponse").msgclass
Comment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Comment").msgclass
