// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comments-srv

package comments_srv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("comments-srv", fileDescriptor_5bce16c516e92068) }

var fileDescriptor_5bce16c516e92068 = []byte{
	// 38 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0x4d, 0xcd, 0x2b, 0x29, 0xd6, 0x2d, 0x2e, 0x2a, 0x03, 0x04, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x0d,
	0x20, 0x41, 0x0e, 0x00, 0x00, 0x00,
}
